spring:
  config:
    import:
  datasource:
    driver-class-name: ${DRIVER}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/main-changelog.yml
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000
  cache:
    type: redis
  jackson:
    mapper:
      require-handlers-for-java8-times: false

auth:
  service:
    url: ${VALIDATE_TOKEN_REQUEST_URL}

registration:
  secret-word: ${MY_SECRET_WORD}

server:
  port: ${PORT}









